package me.ifmo.booking_service.web.request;

import io.swagger.v3.oas.annotations.media.Schema;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

@Schema(description = "Booking to create. id and createdAt are generated by the server.")
public record BookingCreateRequest(
        @NotNull
        @Positive
        @Schema(description = "Person id; the person-ticket pair must be unique.", example = "1", minimum = "1", requiredMode = Schema.RequiredMode.REQUIRED)
        Long personId,

        @NotNull
        @Positive
        @Schema(description = "Existing ticket id, verified through Ticket Service.", example = "105", minimum = "1", requiredMode = Schema.RequiredMode.REQUIRED)
        Long ticketId
) {
}
